### ISSUE TITLE
CPU Temperature Problem

### ISSUE THREAD

**Issue by mioexe** [Lorys89/DELL_LATITUDE_7280#3]
Hello everyone,
I am having a problem with the cpu temperature of my Laptop (i5 7300U).
In idle state it is estimated between 60 and 80 degrees centigrade.
This occurs only with the use of osx, while with windows / linux the temperatures are optimal.
Could anyone tell me why this happens?
Thanks

**Comment by Lorys89** [comment]
Hello, I do not have this problem and we have the same configuration, have you unlocked the cfg?

**Comment by mioexe** [comment]
yes I have unlocked the cfg

**Comment by mioexe** [comment]
could you tell me which version of the bios you use?

**Comment by Lorys89** [comment]
Then I don't know, I don't have this problem.

**Comment by Lorys89** [comment]
my temp to idle state

![Schermata 2022-04-14 alle 11 12 34](https://user-images.githubusercontent.com/64613690/163353853-30302a6d-d26b-4757-b24c-594e2113c73f.png)

**Comment by mioexe** [comment]
which version of the bios do you use?

**Comment by Lorys89** [comment]
> which version of the bios do you use?

last version
