### ISSUE TITLE
7280 with Intel Wifi/Bluetooth

### ISSUE THREAD

**Issue by peretm** [Lorys89/DELL_LATITUDE_7280#5]
Hello, first of all thank you for your work. I managed to patch de BIOS and all the steps and installed Monterrey perfectly.
Unfortunalety my wifi is not a broadcom but an intel (Intel 9560/9260/8265/7265/3165 according the windows driver) as well as the bluetooth (Intel 9560/9260/8265/7265/3165).
Any change to add the ktexts of both in the configuration. 
Many thank again.

**Comment by Lorys89** [comment]
https://github.com/OpenIntelWireless
